# This is a basic workflow to help you get started with Actions

name: CI for Project Proposal

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
    paths:
      - "Project_Proposal/**"
  pull_request:
    branches: [develop]
    paths:
      - "Project_Proposal/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install TeXlive
        run: sudo apt-get update

      - name: Install TeXlive
        run: sudo apt-get -y install texlive texlive-publishers texlive-science latexmk cm-super

      - name: LaTeX Action
        # You may pin to the exact commit or the version.
        # uses: fudan-mse/latex-action@eb2eb7ba472011213ac0a6286fd776494623362c
        uses: fudan-mse/latex-action@v0.0.1
        with:
          # The root LaTeX file to be compiled
          root_file: "project_proposal.tex"
          # The working directory for the LaTeX engine
          working_directory: "Project_Proposal"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "project_charter.pdf"
          path: ${{ github.workspace }}/Project_Proposal/project_charter.pdf
