# This is a basic workflow to help you get started with Actions

name: Team-H-Game-Name (All Platforms)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
    paths:
      - "Team_Hashmi_Project/**"
  pull_request:
    branches: [develop]
    paths:
      - "Team_Hashmi_Project/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          [
            Team_Hashmi_Godot_Game_Linux_x64,
            Team_Hashmi_Godot_Game_Windows_x64,
            Team_Hashmi_Godot_Game_OSX,
          ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: Team_Hashmi_Godot_Game.zip
          preset: ${{ matrix.platform }}
          debugMode: "true"
          # Set true to output an artifact zip file
          package: "true"
          # Location of Godot project in repository
          projectDir: "./Team_Hashmi_Project"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
