# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Echo building Godot Project
        run: echo Building Godot Project!

      # Runs a set of commands using the runners shell
      - name: Build Godot
        # You may pin to the exact commit or the version.
        # uses: josephbmanley/build-godot-action@11589640849ce5bd1bab945c694bb418cb06cb15
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          # Name of the exported binary
          name: Team_H_Godot_Game
          # Name of the preset in `export_presets.cfg` to use
          preset: Team_H_Godot_Game_OSX
          # Optional name of the subdirectory to put exported project in
          subdirectory: ./Team_H_Project/Output
          # Set true to output an artifact zip file
          package: true
          # Location of Godot project in repository
          projectDir: ./Team_H_Project
          # Whether or not to use `--export-debug`
          debugMode: true


      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Team_H_Godot_Game_OSX
          # A file, directory or wildcard pattern that describes what to upload
          path: ./Team_H_Project/Output
          # The desired behavior if no files are found using the provided path.
          #Available Options:
          warn: Output a warning but do not fail the action
          error: Fail the action with an error message
          ignore: Do not output any warnings or errors, the action does not fail

          # Duration after which artifact will expire in days. 0 means using default retention.
          #Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          retention-days: 0
