name: Team-Hashmi BananaMania (All Platforms)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
    paths:
      - "Team_Hashmi_Project/**"
  pull_request:
    branches: [develop]
    paths:
      - "Team_Hashmi_Project/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          [
            Team_Hashmi_Godot_Game_Linux_x64,
            Team_Hashmi_Godot_Game_Windows_x64,
            Team_Hashmi_Godot_Game_OSX,
          ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: godot-tester
        # You may pin to the exact commit or the version.
        # uses: croconut/godot-tester@c4a23e6bc4b4a2646686bdc391823ed6ef083206
        uses: croconut/godot-tester@v2.4
        with:
          # Your Godot version number e.g. 3.2.2
          version: "3.3.4"
          path: "./Team_Hashmi_Project"
          # how long to spend importing assets before tests are run
          import-time: "5"
          test-timeout: 300
          minimum-pass: 1
          # Maximum number of failing asserts or tests, if this or pass rate fails then the action will fail. Is not checked if you do not set it
          max-fails: 0
      # - name: Build
      #   id: build
      #   uses: josephbmanley/build-godot-action@v1.4.1
      #   with:
      #     name: Team_Hashmi_Godot_Game.zip
      #     preset: ${{ matrix.platform }}
      #     debugMode: "true"
      #     # Set true to output an artifact zip file
      #     package: "true"
      #     # Location of Godot project in repository
      #     projectDir: "./Team_Hashmi_Project"
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Client - ${{ matrix.platform }}
      #     path: ${{ github.workspace }}/${{ steps.build.outputs.build }}

  export-windows:
    env:
      GODOT_VERSION: 3.3.4
      EXPORT_NAME: Banana_Mania
      GITHUB_WORKSPACE: ${{ github.workspace }}
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
      - name: Windows Build
        run: |
          cd ./Team_Hashmi_Project
          mkdir bin
          godot -v --export "Team_Hashmi_Godot_Game_Windows_x64" $GITHUB_WORKSPACE/Team_Hashmi_Project/bin/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: $GITHUB_WORKSPACE/Team_Hashmi_Project/bin

  export-linux:
    env:
      GODOT_VERSION: 3.3.4
      EXPORT_NAME: Banana_Mania
      GITHUB_WORKSPACE: ${{ github.workspace }}
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
      - name: Linux Build
        run: |
          cd ./Team_Hashmi_Project
          mkdir bin
          godot -v --export "Team_Hashmi_Godot_Game_Linux_x64" $GITHUB_WORKSPACE/Team_Hashmi_Project/bin/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: $GITHUB_WORKSPACE/Team_Hashmi_Project/bin

  export-mac:
    env:
      GODOT_VERSION: 3.3.4
      EXPORT_NAME: Banana_Mania
      GITHUB_WORKSPACE: ${{ github.workspace }}
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
      - name: Mac Build
        run: |
          cd ./Team_Hashmi_Project
          mkdir bin
          godot -v --export "Team_Hashmi_Godot_Game_OSX" $GITHUB_WORKSPACE/Team_Hashmi_Project/bin/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: $GITHUB_WORKSPACE/Team_Hashmi_Project/bin
