# This is a basic workflow to help you get started with Actions

name: Team-Hashmi README

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
    paths:
      - "Meetings_And_Attendance/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.2
        with:
          # Python script
          script: "replace.py"

    
    
      - name: Github commit and push
        # You may pin to the exact commit or the version.
        # uses: Smart-Transportation/push@c77535fe7a94645f7ceca83e48e6cc977620710e
        uses: Smart-Transportation/push@v1.3
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.UPDATE_README_TOKEN }}
          # Email used to configure user.email in `git config`.
          message: "README.md update"
          branch: "develop"
    
